packages:
  - studio
  - app

catalog:
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@types/lodash': ^4.17.20
  '@types/node': ^24.7.0
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  eslint: ^9.37.0
  lodash: 4.17.21
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
  typescript-plugin-css-modules: ^5.2.0
