packages:
  - studio
  - app

catalog:
  '@ianvs/prettier-plugin-sort-imports': 4.7.0
  '@types/lodash': 4.17.20
  '@types/node': 24.7.2
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.1
  change-case: ^5.4.4
  eslint: 9.37.0
  lodash: ^4.17.21
  prettier: 3.6.2
  react: 19.2.0
  react-dom: 19.2.0
  solid-js: ^1.9.9
  title-case: ^4.3.2
  typescript: 5.9.3
  typescript-plugin-css-modules: 5.2.0
